tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#B5493C",
        "background": "#F7F1E8",
        "secondary": "#2B2320",
        "accent": "#7A8B6F",
        "background-light": "#F7F1E8",
        "background-dark": "#2B2320",
        // Nuevos colores del tema Card-Scalloped
        "tertiary": "#49583f",
        "surface": "#fff9ef",
        "on-secondary-fixed": "#081c33",
        "primary-fixed-dim": "#ffb4a9",
        "tertiary-container": "#607156",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#83251b",
        "tertiary-fixed": "#d6e8c8",
        "secondary-container": "#cee1ff",
        "primary-fixed": "#ffdad5",
        "surface-bright": "#fff9ef",
        "surface-container": "#f3ede4",
        "on-secondary-container": "#52647d",
        "on-tertiary-container": "#e2f4d3",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#364860",
        "on-primary-container": "#ffe9e6",
        "inverse-primary": "#ffb4a9",
        "on-tertiary-fixed": "#111f0b",
        "on-surface-variant": "#57423f",
        "primary-container": "#b5493c",
        "outline": "#8a716e",
        "on-background": "#1d1b16",
        "on-error-container": "#93000a",
        "surface-dim": "#dfd9d1",
        "charcoal-text": "#2B2320",
        "on-tertiary-fixed-variant": "#3c4b33",
        "surface-container-high": "#ede7df",
        "inverse-surface": "#32302a",
        "on-primary-fixed": "#410000",
        "tertiary-fixed-dim": "#baccad",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e7e2d9",
        "secondary-fixed": "#d3e4ff",
        "tan-neutral": "#C9A876",
        "secondary-fixed-dim": "#b5c8e5",
        "surface-container-low": "#f9f3ea",
        "surface-variant": "#e7e2d9",
        "surface-tint": "#a33c30",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#ddc0bb",
        "on-surface": "#1d1b16",
        "inverse-on-surface": "#f6f0e7",
        "terracotta": "#b5493c",
        "cream": "#f7f1e8",
        "navy": "#2c3e56",
        "sage": "#7a8b6f"
      },
      fontFamily: {
        "display": ["Quicksand", "sans-serif"],
        "heading": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "display-lg": ["Quicksand", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "label-sm": ["Quicksand", "sans-serif"],
        "body-lg": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "label-lg": ["Quicksand", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      boxShadow: {
        'paper': '0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.01)',
        'paper-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.03)',
        'playful': '4px 4px 0px #e2d1f9',
        'playful-hover': '6px 6px 0px #B5493C',
      }
    },
  },
};
